name: pikvm-os

on: [push, pull_request]

jobs:
  os:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: aarch64
        run: ./mk-gen-aarch64.sh
    
