name: create release with assets

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  REPO_URL: http://il.us.mirror.archlinuxarm.org
  BUILDER_URL: https://github.com/${{ github.repository_owner }}/pi-builder
  PIKVM_REPO_URL: ${{ secrets.PIKVM_REPO_URL }}
  PIKVM_REPO_KEY: ${{ secrets.PIKVM_REPO_KEY }}
  TIMEZONE: America/New_York
  CARD_DATA_FS_TYPE: ext4

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ''
          draft: false
          prerelease: false
    outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}

  build:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        include:
          - uboot: libretech-all-h3-cc-h2-plus
            arch: arm
            board: generic
            platform: v2-hdmiusb
            
          - uboot: libretech-all-h3-cc-h3
            arch: arm
            board: generic
            platform: v2-hdmiusb 
            
          - uboot: orangepi-one
            arch: arm
            board: generic
            platform: v2-hdmiusb
            
          - uboot: orangepi-zero
            arch: arm
            board: generic
            platform: v2-hdmiusb
            
          - uboot: orangepi-2
            arch: arm
            board: generic
            platform: v2-hdmiusb
            
          - uboot: nanopi-neo
            arch: arm
            board: generic
            platform: v2-hdmiusb
            
          - uboot: nanopi-m1
            arch: arm
            board: generic
            platform: v2-hdmiusb
            
          - uboot: nanopi-m1-plus
            arch: arm
            board: generic
            platform: v2-hdmiusb
            
          - uboot: rock64-rk3328
            arch: aarch64
            board: generic
            platform: v2-hdmiusb

          - uboot: nanopi-r2s-rk3328
            arch: aarch64
            board: generic
            platform: v2-hdmiusb

          - uboot: roc-cc-rk3328
            arch: aarch64
            board: generic
            platform: v2-hdmiusb           
    name: build ${{ matrix.platform }}-${{ matrix.board }}-${{ matrix.arch }}-${{ matrix.uboot }}
    env:
      BOARD: ${{ matrix.board }}
      ARCH: ${{ matrix.arch }}
      UBOOT: ${{ matrix.uboot }}
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: show environment
        run: env && df -h

      - name: make os
        run: make os

      - name: make image
        run: make image

      - name: upload image
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }} 
          asset_path: images/${{ matrix.platform }}-${{ matrix.board }}-${{ matrix.arch }}-${{ matrix.uboot }}.img.bz2
          asset_name: ${{ matrix.platform }}-${{ matrix.board }}-${{ matrix.arch }}-${{ matrix.uboot }}.img.bz2
          asset_content_type: application/x-bzip2
